version: '3.8'

services:
  usuario-service:
    build:
      context: ./usuario-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://usuario-db:3306/usuarioDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - usuario-db
    networks:
      - gestao-pedidos-microservicos

  catalogo-produtos-service:
    build:
      context: ./catalogo-produtos-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://catalogo-produtos-db:3306/catalogoProdutosDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      USUARIO_SERVICE_URL: http://usuario-service:8081
    depends_on:
      - catalogo-produtos-db
      - usuario-service
    networks:
      - gestao-pedidos-microservicos

  pedidos-service:
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pedidos-db:3306/pedidosDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      USUARIO_SERVICE_URL: http://usuario-service:8081
      PRODUTO_SERVICE_URL: http://catalogo-produtos-service:8082
    depends_on:
      - pedidos-db
      - usuario-service
      - catalogo-produtos-service
    networks:
      - gestao-pedidos-microservicos

  gestao-pedidos-web:
    build:
      context: ./gestao-pedidos-web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - usuario-service
      - catalogo-produtos-service
      - pedidos-service
    networks:
      - gestao-pedidos-microservicos

  usuario-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: usuarioDB
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gestao-pedidos-microservicos
    ports:
      - "3307:3306"

  catalogo-produtos-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: catalogoProdutosDB
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gestao-pedidos-microservicos
    ports:
      - "3308:3306"

  pedidos-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: pedidosDB
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gestao-pedidos-microservicos
    ports:
      - "3309:3306"


networks:
  gestao-pedidos-microservicos:
    driver: bridge